@startuml flow

actor User
participant App
box IMKit
  participant RCKitApplication
  participant RCKitContext
  participant RCKitStore
  participant RCKitModule
  participant RCKitProvider
end box
participant IMLib
box DOM
  participant "<rc-xxx-provider>" as Provider
  participant "<rc-xxx>" as Comoponent
end box

== IM 事件 ==

IMLib -> RCKitContext: 通知连接状态变更
RCKitContext --> RCKitModule: 事件分发
RCKitModule --> RCKitModule: 业务逻辑处理
alt 按需
  RCKitModule --> RCKitStore: 修改内存数据
end
alt 按需
  RCKitModule --> RCKitContext: 其他业务通知
end
RCKitContext --> Provider: 事件分发
Provider --> Provider: ViewModel 修改
Provider --> Comoponent: ViewModel 驱动 UI 变更
IMLib -> App: 通知业务层

== UI 交互事件 ==

User -> Comoponent: 交互事件
Comoponent -> Provider: 交互事件
Provider --> Provider: 处理交互事件
alt 按需
  Provider --> RCKitContext: 业务事件通知
end
alt 按需
  Provider --> Provider: ViewModel 修改
  Provider --> Comoponent: ViewModel 驱动 UI 变更
end

@enduml
