@startuml msg-send

actor User
participant Input as IC
participant MessageList as MC
participant MessageModdule as MM
participant "发送队列" as MQ
participant "上传队列" as UQ
participant IMLib

User -> IC: 发送文件
IC --> MM: sendFileMessage(file)
MM --> MM: 生成 KitMessageId\n维护与 IMLib messageId 的映射关系
MM --> MM: 插入本地消息列表
MM --> MC: RCKitEvents.INSERT_MESSAGE KitMessageId
note right: 派发事件更新消息列表
MM --> MQ: 插入发送队列，由队列统一管理发送，以处理并发与限频问题
== 发送队列处理 ==
MQ --> MQ: pickone
MQ --> IMLib: messageId = sendFileMessage(file, hooks)
loop
IMLib --> MM: 进度反馈
MM --> MC: RCKitEvents.FILE_UPLOAD_PROGRESS
note right: 派发事件更新上传进度(kitMessageId)
IMLib -->

end

@enduml